version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: bdd
    ports:
      - "5433:5432"
    volumes:
      - PostgreSQLdb:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d/

  api:
    build: .
    ports:
      - "3004:3004"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules